// Date: 6/6/2014 4:08:16 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMug extends ModelBase
{
  //fields
    ModelRenderer MugSide1;
    ModelRenderer MugSide2;
    ModelRenderer MugSide3;
    ModelRenderer MugSide4;
    ModelRenderer MugBase;
    ModelRenderer MugHandle1;
    ModelRenderer MugHandle2;
    ModelRenderer MugHandle3;
    ModelRenderer MugContents;
  
  public ModelMug()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      MugSide1 = new ModelRenderer(this, 27, 22);
      MugSide1.addBox(0F, 0F, 0F, 4, 6, 1);
      MugSide1.setRotationPoint(-2F, 18F, 2F);
      MugSide1.setTextureSize(64, 64);
      MugSide1.mirror = true;
      setRotation(MugSide1, 0F, 0F, 0F);
      MugSide2 = new ModelRenderer(this, 12, 26);
      MugSide2.addBox(-2F, 0F, 0F, 1, 6, 5);
      MugSide2.setRotationPoint(-1F, 18F, -2F);
      MugSide2.setTextureSize(64, 64);
      MugSide2.mirror = true;
      setRotation(MugSide2, 0F, 0F, 0F);
      MugSide3 = new ModelRenderer(this, 40, 26);
      MugSide3.addBox(0F, 0F, 0F, 1, 6, 5);
      MugSide3.setRotationPoint(2F, 18F, -2F);
      MugSide3.setTextureSize(64, 64);
      MugSide3.mirror = true;
      setRotation(MugSide3, 0F, 0F, 0F);
      MugSide4 = new ModelRenderer(this, 27, 38);
      MugSide4.addBox(0F, 0F, 0F, 4, 6, 1);
      MugSide4.setRotationPoint(-2F, 18F, -2F);
      MugSide4.setTextureSize(64, 64);
      MugSide4.mirror = true;
      setRotation(MugSide4, 0F, 0F, 0F);
      MugBase = new ModelRenderer(this, 21, 46);
      MugBase.addBox(0F, 0F, 0F, 6, 1, 5);
      MugBase.setRotationPoint(-3F, 23F, -2F);
      MugBase.setTextureSize(64, 64);
      MugBase.mirror = true;
      setRotation(MugBase, 0F, 0F, 0F);
      MugHandle1 = new ModelRenderer(this, 53, 29);
      MugHandle1.addBox(0F, 0F, 0F, 2, 1, 1);
      MugHandle1.setRotationPoint(3F, 19F, 0F);
      MugHandle1.setTextureSize(64, 64);
      MugHandle1.mirror = true;
      setRotation(MugHandle1, 0F, 0F, 0F);
      MugHandle2 = new ModelRenderer(this, 55, 32);
      MugHandle2.addBox(0F, 0F, 0F, 1, 3, 1);
      MugHandle2.setRotationPoint(4F, 20F, 0F);
      MugHandle2.setTextureSize(64, 64);
      MugHandle2.mirror = true;
      setRotation(MugHandle2, 0F, 0F, 0F);
      MugHandle3 = new ModelRenderer(this, 53, 37);
      MugHandle3.addBox(0F, 0F, 0F, 2, 1, 1);
      MugHandle3.setRotationPoint(3F, 22F, 0F);
      MugHandle3.setTextureSize(64, 64);
      MugHandle3.mirror = true;
      setRotation(MugHandle3, 0F, 0F, 0F);
      MugContents = new ModelRenderer(this, 25, 30);
      MugContents.addBox(0F, 0F, 0F, 4, 4, 3);
      MugContents.setRotationPoint(-2F, 19F, -1F);
      MugContents.setTextureSize(64, 64);
      MugContents.mirror = true;
      setRotation(MugContents, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    MugSide1.render(f5);
    MugSide2.render(f5);
    MugSide3.render(f5);
    MugSide4.render(f5);
    MugBase.render(f5);
    MugHandle1.render(f5);
    MugHandle2.render(f5);
    MugHandle3.render(f5);
    MugContents.render(f5);
  }
  
  public void renderModel(float f)
  {
	  MugSide1.render(f);
	  MugSide2.render(f);
	  MugSide3.render(f);
	  MugSide4.render(f);
	  MugBase.render(f);
	  MugHandle1.render(f);
	  MugHandle2.render(f);
	  MugHandle3.render(f);
	  MugContents.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
