// Date: 6/6/2014 3:15:09 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTableLarge extends ModelBase
{
  //fields
    ModelRenderer FrontRightLeg;
    ModelRenderer FrontLeftLeg;
    ModelRenderer BackRightLeg;
    ModelRenderer BackLeftLeg;
    ModelRenderer TableTop;
  
  public ModelTableLarge()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      FrontRightLeg = new ModelRenderer(this, 0, 43);
      FrontRightLeg.addBox(0F, 0F, 0F, 1, 10, 1);
      FrontRightLeg.setRotationPoint(-7F, 14F, -7F);
      FrontRightLeg.setTextureSize(128, 128);
      FrontRightLeg.mirror = true;
      setRotation(FrontRightLeg, 0F, 0F, 0F);
      FrontLeftLeg = new ModelRenderer(this, 12, 43);
      FrontLeftLeg.addBox(0F, 0F, 0F, 1, 10, 1);
      FrontLeftLeg.setRotationPoint(22F, 14F, -7F);
      FrontLeftLeg.setTextureSize(128, 128);
      FrontLeftLeg.mirror = true;
      setRotation(FrontLeftLeg, 0F, 0F, 0F);
      BackRightLeg = new ModelRenderer(this, 6, 43);
      BackRightLeg.addBox(0F, 0F, 0F, 1, 10, 1);
      BackRightLeg.setRotationPoint(-7F, 14F, 22F);
      BackRightLeg.setTextureSize(128, 128);
      BackRightLeg.mirror = true;
      setRotation(BackRightLeg, 0F, 0F, 0F);
      BackLeftLeg = new ModelRenderer(this, 18, 43);
      BackLeftLeg.addBox(0F, 0F, 0F, 1, 10, 1);
      BackLeftLeg.setRotationPoint(22F, 14F, 22F);
      BackLeftLeg.setTextureSize(128, 128);
      BackLeftLeg.mirror = true;
      setRotation(BackLeftLeg, 0F, 0F, 0F);
      TableTop = new ModelRenderer(this, 0, 56);
      TableTop.addBox(0F, 0F, 0F, 32, 1, 32);
      TableTop.setRotationPoint(-8F, 13F, -8F);
      TableTop.setTextureSize(128, 128);
      TableTop.mirror = true;
      setRotation(TableTop, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    FrontRightLeg.render(f5);
    FrontLeftLeg.render(f5);
    BackRightLeg.render(f5);
    BackLeftLeg.render(f5);
    TableTop.render(f5);
  }
  
  public void renderModel(float f)
  {
	  FrontRightLeg.render(f);
	  FrontLeftLeg.render(f);
	  BackRightLeg.render(f);
	  BackLeftLeg.render(f);
	  TableTop.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
