// Date: 6/7/2014 3:10:15 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelComfyChair extends ModelBase
{
  //fields
    ModelRenderer BottomCushion;
    ModelRenderer TopCushion;
    ModelRenderer LeftArm;
    ModelRenderer RightArm;
    ModelRenderer ChairBack;
    ModelRenderer LegRest;
  
  public ModelComfyChair()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      BottomCushion = new ModelRenderer(this, 35, 92);
      BottomCushion.addBox(0F, 0F, 0F, 14, 4, 15);
      BottomCushion.setRotationPoint(-7F, 20F, -8F);
      BottomCushion.setTextureSize(128, 128);
      BottomCushion.mirror = true;
      setRotation(BottomCushion, 0F, 0F, 0F);
      TopCushion = new ModelRenderer(this, 36, 74);
      TopCushion.addBox(0F, 0F, 0F, 14, 3, 14);
      TopCushion.setRotationPoint(-7F, 17F, -7F);
      TopCushion.setTextureSize(128, 128);
      TopCushion.mirror = true;
      setRotation(TopCushion, 0F, 0F, 0F);
      LeftArm = new ModelRenderer(this, 90, 48);
      LeftArm.addBox(0F, 0F, 0F, 4, 10, 15);
      LeftArm.setRotationPoint(4F, 14F, -8F);
      LeftArm.setTextureSize(128, 128);
      LeftArm.mirror = true;
      setRotation(LeftArm, 0F, 0F, 0F);
      RightArm = new ModelRenderer(this, 0, 48);
      RightArm.addBox(0F, 0F, 0F, 4, 10, 15);
      RightArm.setRotationPoint(-8F, 14F, -8F);
      RightArm.setTextureSize(128, 128);
      RightArm.mirror = true;
      setRotation(RightArm, 0F, 0F, 0F);
      ChairBack = new ModelRenderer(this, 43, 48);
      ChairBack.addBox(0F, -20F, 0F, 16, 20, 5);
      ChairBack.setRotationPoint(-8F, 23F, 2F);
      ChairBack.setTextureSize(128, 128);
      ChairBack.mirror = true;
      setRotation(ChairBack, -0.2792527F, 0F, 0F);
      LegRest = new ModelRenderer(this, 43, 112);
      LegRest.addBox(0F, -2F, -5F, 16, 2, 5);
      LegRest.setRotationPoint(-8F, 21F, -7F);
      LegRest.setTextureSize(128, 128);
      LegRest.mirror = true;
      setRotation(LegRest, 0.6457718F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BottomCushion.render(f5);
    TopCushion.render(f5);
    LeftArm.render(f5);
    RightArm.render(f5);
    ChairBack.render(f5);
    LegRest.render(f5);
  }
  
  public void renderModel(float f)
  {
    BottomCushion.render(f);
    TopCushion.render(f);
    LeftArm.render(f);
    RightArm.render(f);
    ChairBack.render(f);
    LegRest.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
