// Date: 6/6/2014 3:23:11 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTableSmall extends ModelBase
{
  //fields
    ModelRenderer BackLeftLeg;
    ModelRenderer BackRightLeg;
    ModelRenderer FrontLeftLeg;
    ModelRenderer FrontRightLeg;
    ModelRenderer TableTop;
  
  public ModelTableSmall()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      BackLeftLeg = new ModelRenderer(this, 2, 12);
      BackLeftLeg.addBox(0F, 0F, 0F, 1, 16, 1); // (0F, 0F, 0F, 1, 10, 1)
      BackLeftLeg.setRotationPoint(-7F, 9F, 6F); // (-7F, 14F, 6F)
      BackLeftLeg.setTextureSize(64, 64);
      BackLeftLeg.mirror = true;
      setRotation(BackLeftLeg, 0F, 0F, 0F);
      BackRightLeg = new ModelRenderer(this, 8, 12);
      BackRightLeg.addBox(0F, 0F, 0F, 1, 16, 1); // (0F, 0F, 0F, 1, 10, 1)
      BackRightLeg.setRotationPoint(6F, 9F, 6F); // (6F, 14F, 6F)
      BackRightLeg.setTextureSize(64, 64);
      BackRightLeg.mirror = true;
      setRotation(BackRightLeg, 0F, 0F, 0F);
      FrontLeftLeg = new ModelRenderer(this, 14, 12);
      FrontLeftLeg.addBox(0F, 0F, 0F, 1, 16, 1); // (0F, 0F, 0F, 1, 10, 1)
      FrontLeftLeg.setRotationPoint(-7F, 9F, -7F); // (-7F, 14F, -7F)
      FrontLeftLeg.setTextureSize(64, 64);
      FrontLeftLeg.mirror = true;
      setRotation(FrontLeftLeg, 0F, 0F, 0F);
      FrontRightLeg = new ModelRenderer(this, 20, 12);
      FrontRightLeg.addBox(0F, 0F, 0F, 1, 16, 1); // (0F, 0F, 0F, 1, 10, 1)
      FrontRightLeg.setRotationPoint(6F, 9F, -7F); // (6F, 14F, -7F)
      FrontRightLeg.setTextureSize(64, 64);
      FrontRightLeg.mirror = true;
      setRotation(FrontRightLeg, 0F, 0F, 0F);
      TableTop = new ModelRenderer(this, 0, 24); // okay... model starts at height 11, so either add or subtract 5 to rot. point y!
      TableTop.addBox(0F, 0F, 0F, 16, 1, 16);
      TableTop.setRotationPoint(-8F, 8F, -8F); // y was 13F, SUBTRACT 5!!!
      TableTop.setTextureSize(64, 64);
      TableTop.mirror = true;
      setRotation(TableTop, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BackLeftLeg.render(f5);
    BackRightLeg.render(f5);
    FrontLeftLeg.render(f5);
    FrontRightLeg.render(f5);
    TableTop.render(f5);
  }
  
  public void renderModel(float f)
  {
	BackLeftLeg.render(f);
	BackRightLeg.render(f);
	FrontLeftLeg.render(f);
	FrontRightLeg.render(f);
	TableTop.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
