// Date: 6/9/2014 12:12:49 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBookshelf extends ModelBase
{
  //fields
    ModelRenderer FrameLeft;
    ModelRenderer FrameRight;
    ModelRenderer FrameBack;
    ModelRenderer FrameBottom;
    ModelRenderer FrameTop;
    ModelRenderer FrameMiddle;
    ModelRenderer Book1;
    ModelRenderer Book2;
    ModelRenderer Book3;
    ModelRenderer Book4;
    ModelRenderer Book5;
    ModelRenderer Book6;
    ModelRenderer Book7;
    ModelRenderer Book8;
    ModelRenderer Book9;
    ModelRenderer Book10;
    ModelRenderer Book11;
    ModelRenderer Book12;
    ModelRenderer Book13;
    ModelRenderer Book14;
    ModelRenderer Book15;
    ModelRenderer Book16;
    ModelRenderer Book17;
    ModelRenderer Book18;
    ModelRenderer Book19;
    ModelRenderer Book20;
  
  public ModelBookshelf()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      FrameLeft = new ModelRenderer(this, 1, 48);
      FrameLeft.addBox(0F, 0F, 0F, 1, 14, 16);
      FrameLeft.setRotationPoint(-8F, 9F, -8F);
      FrameLeft.setTextureSize(128, 128);
      FrameLeft.mirror = true;
      setRotation(FrameLeft, 0F, 0F, 0F);
      FrameRight = new ModelRenderer(this, 93, 48);
      FrameRight.addBox(0F, 0F, 0F, 1, 14, 16);
      FrameRight.setRotationPoint(7F, 9F, -8F);
      FrameRight.setTextureSize(128, 128);
      FrameRight.mirror = true;
      setRotation(FrameRight, 0F, 0F, 0F);
      FrameBack = new ModelRenderer(this, 42, 24);
      FrameBack.addBox(0F, 0F, 0F, 14, 14, 8);
      FrameBack.setRotationPoint(-7F, 9F, 0F);
      FrameBack.setTextureSize(128, 128);
      FrameBack.mirror = true;
      setRotation(FrameBack, 0F, 0F, 0F);
      FrameBottom = new ModelRenderer(this, 32, 91);
      FrameBottom.addBox(0F, 0F, 0F, 16, 1, 16);
      FrameBottom.setRotationPoint(-8F, 23F, -8F);
      FrameBottom.setTextureSize(128, 128);
      FrameBottom.mirror = true;
      setRotation(FrameBottom, 0F, 0F, 0F);
      FrameTop = new ModelRenderer(this, 32, 5);
      FrameTop.addBox(0F, 0F, 0F, 16, 1, 16);
      FrameTop.setRotationPoint(-8F, 8F, -8F);
      FrameTop.setTextureSize(128, 128);
      FrameTop.mirror = true;
      setRotation(FrameTop, 0F, 0F, 0F);
      FrameMiddle = new ModelRenderer(this, 32, 109);
      FrameMiddle.addBox(0F, 0F, 0F, 16, 2, 16);
      FrameMiddle.setRotationPoint(-8F, 15F, -8F);
      FrameMiddle.setTextureSize(128, 128);
      FrameMiddle.mirror = true;
      setRotation(FrameMiddle, 0F, 0F, 0F);
      Book1 = new ModelRenderer(this, 36, 48);
      Book1.addBox(0F, -6F, 0F, 1, 6, 5);
      Book1.setRotationPoint(-7F, 15F, -5F);
      Book1.setTextureSize(128, 128);
      Book1.mirror = true;
      setRotation(Book1, 0F, 0F, 0F);
      Book2 = new ModelRenderer(this, 49, 48);
      Book2.addBox(0F, -6F, 0F, 1, 6, 5);
      Book2.setRotationPoint(-5F, 15F, -5F);
      Book2.setTextureSize(128, 128);
      Book2.mirror = true;
      setRotation(Book2, 0F, 0F, -0.1570796F);
      Book3 = new ModelRenderer(this, 62, 48);
      Book3.addBox(0F, -6F, 0F, 1, 6, 5);
      Book3.setRotationPoint(-3F, 15F, -6F);
      Book3.setTextureSize(128, 128);
      Book3.mirror = true;
      setRotation(Book3, 0F, 0F, -0.296706F);
      Book4 = new ModelRenderer(this, 75, 48);
      Book4.addBox(0F, 0F, 0F, 1, 6, 5);
      Book4.setRotationPoint(-2F, 9F, -5F);
      Book4.setTextureSize(128, 128);
      Book4.mirror = true;
      setRotation(Book4, 0F, 0F, 0F);
      Book5 = new ModelRenderer(this, 36, 60);
      Book5.addBox(0F, 0F, 0F, 1, 6, 5);
      Book5.setRotationPoint(-1F, 9F, -6F);
      Book5.setTextureSize(128, 128);
      Book5.mirror = true;
      setRotation(Book5, 0F, 0F, 0F);
      Book6 = new ModelRenderer(this, 49, 60);
      Book6.addBox(0F, -6F, 0F, 1, 6, 5);
      Book6.setRotationPoint(1F, 15F, -6F);
      Book6.setTextureSize(128, 128);
      Book6.mirror = true;
      setRotation(Book6, 0F, 0F, -0.1570796F);
      Book7 = new ModelRenderer(this, 62, 60);
      Book7.addBox(0F, -6F, 0F, 1, 6, 5);
      Book7.setRotationPoint(3F, 15F, -7F);
      Book7.setTextureSize(128, 128);
      Book7.mirror = true;
      setRotation(Book7, 0F, 0F, -0.3141593F);
      Book8 = new ModelRenderer(this, 75, 60);
      Book8.addBox(0F, 0F, 0F, 1, 6, 5);
      Book8.setRotationPoint(4F, 9F, -5F);
      Book8.setTextureSize(128, 128);
      Book8.mirror = true;
      setRotation(Book8, 0F, 0F, 0F);
      Book9 = new ModelRenderer(this, 36, 72);
      Book9.addBox(0F, 0F, 0F, 1, 6, 5);
      Book9.setRotationPoint(5F, 9F, -5F);
      Book9.setTextureSize(128, 128);
      Book9.mirror = true;
      setRotation(Book9, 0F, 0F, 0F);
      Book10 = new ModelRenderer(this, 49, 72);
      Book10.addBox(0F, 0F, 0F, 1, 6, 5);
      Book10.setRotationPoint(6F, 9F, -7F);
      Book10.setTextureSize(128, 128);
      Book10.mirror = true;
      setRotation(Book10, 0F, 0F, 0F);
      Book11 = new ModelRenderer(this, 62, 72);
      Book11.addBox(0F, 0F, 0F, 1, 6, 5);
      Book11.setRotationPoint(-7F, 17F, -7F);
      Book11.setTextureSize(128, 128);
      Book11.mirror = true;
      setRotation(Book11, 0F, 0F, -0.0872665F);
      Book12 = new ModelRenderer(this, 75, 72);
      Book12.addBox(0F, 0F, 0F, 1, 6, 5);
      Book12.setRotationPoint(-5F, 17F, -6F);
      Book12.setTextureSize(128, 128);
      Book12.mirror = true;
      setRotation(Book12, 0F, 0F, 0F);
      Book13 = new ModelRenderer(this, 19, 79);
      Book13.addBox(0F, 0F, 0F, 1, 6, 5);
      Book13.setRotationPoint(-3F, 17F, -6F);
      Book13.setTextureSize(128, 128);
      Book13.mirror = true;
      setRotation(Book13, 0F, 0F, 0F);
      Book14 = new ModelRenderer(this, 19, 91);
      Book14.addBox(0F, 0F, 0F, 1, 6, 5);
      Book14.setRotationPoint(-2F, 17F, -5F);
      Book14.setTextureSize(128, 128);
      Book14.mirror = true;
      setRotation(Book14, 0F, 0F, 0F);
      Book15 = new ModelRenderer(this, 19, 103);
      Book15.addBox(0F, 0F, 0F, 1, 6, 5);
      Book15.setRotationPoint(-1F, 17F, -5F);
      Book15.setTextureSize(128, 128);
      Book15.mirror = true;
      setRotation(Book15, 0F, 0F, 0F);
      Book16 = new ModelRenderer(this, 19, 115);
      Book16.addBox(0F, 0F, 0F, 1, 6, 5);
      Book16.setRotationPoint(0F, 17F, -7F);
      Book16.setTextureSize(128, 128);
      Book16.mirror = true;
      setRotation(Book16, 0F, 0F, -0.0698132F);
      Book17 = new ModelRenderer(this, 97, 79);
      Book17.addBox(0F, -6F, 0F, 1, 6, 5);
      Book17.setRotationPoint(2F, 23F, -7F);
      Book17.setTextureSize(128, 128);
      Book17.mirror = true;
      setRotation(Book17, 0F, 0F, -0.0872665F);
      Book18 = new ModelRenderer(this, 97, 91);
      Book18.addBox(0F, 0F, 0F, 1, 6, 5);
      Book18.setRotationPoint(3F, 17F, -6F);
      Book18.setTextureSize(128, 128);
      Book18.mirror = true;
      setRotation(Book18, 0F, 0F, 0F);
      Book19 = new ModelRenderer(this, 97, 103);
      Book19.addBox(0F, -6F, 0F, 1, 6, 5);
      Book19.setRotationPoint(4F, 23F, -5F);
      Book19.setTextureSize(128, 128);
      Book19.mirror = true;
      setRotation(Book19, 0F, 0F, 0.1570796F);
      Book20 = new ModelRenderer(this, 97, 115);
      Book20.addBox(0F, -6F, 0F, 1, 6, 5);
      Book20.setRotationPoint(5F, 23F, -8F);
      Book20.setTextureSize(128, 128);
      Book20.mirror = true;
      setRotation(Book20, 0F, 0F, 0.1570796F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    FrameLeft.render(f5);
    FrameRight.render(f5);
    FrameBack.render(f5);
    FrameBottom.render(f5);
    FrameTop.render(f5);
    FrameMiddle.render(f5);
    Book1.render(f5);
    Book2.render(f5);
    Book3.render(f5);
    Book4.render(f5);
    Book5.render(f5);
    Book6.render(f5);
    Book7.render(f5);
    Book8.render(f5);
    Book9.render(f5);
    Book10.render(f5);
    Book11.render(f5);
    Book12.render(f5);
    Book13.render(f5);
    Book14.render(f5);
    Book15.render(f5);
    Book16.render(f5);
    Book17.render(f5);
    Book18.render(f5);
    Book19.render(f5);
    Book20.render(f5);
  }
  
  public void renderModel(float f)
  {
	FrameLeft.render(f);
    FrameRight.render(f);
    FrameBack.render(f);
    FrameBottom.render(f);
    FrameTop.render(f);
    FrameMiddle.render(f);
    Book1.render(f);
    Book2.render(f);
    Book3.render(f);
    Book4.render(f);
    Book5.render(f);
    Book6.render(f);
    Book7.render(f);
    Book8.render(f);
    Book9.render(f);
    Book10.render(f);
    Book11.render(f);
    Book12.render(f);
    Book13.render(f);
    Book14.render(f);
    Book15.render(f);
    Book16.render(f);
    Book17.render(f);
    Book18.render(f);
    Book19.render(f);
    Book20.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
