// Date: 8/14/2014 9:56:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAetherialArmor extends ModelBiped
{
  //fields
    ModelRenderer LeftPauldron;
    ModelRenderer RightPauldron;
    ModelRenderer ChestPiece;
    ModelRenderer LeftElbow;
    ModelRenderer RightElbow;
    ModelRenderer LeftPantLeg;
    ModelRenderer Helmet2;
    ModelRenderer Helmet3;
    ModelRenderer Helmet4;
    ModelRenderer Helmet5;
    ModelRenderer Helmet6;
    ModelRenderer Helmet7;
    ModelRenderer RightPantLeg;
    ModelRenderer RightFoot;
    ModelRenderer LeftFoot;
    ModelRenderer BackPlate;
    ModelRenderer RightWing;
    ModelRenderer LeftWing;
  
  public ModelAetherialArmor(float scale)
  {
	super(scale, 0, 128, 128);
    textureWidth = 128;
    textureHeight = 128;
    setTextureOffset("RightWing.RightWingStem", 23, 20);
    setTextureOffset("RightWing.RightWing1", 17, 17);
    setTextureOffset("RightWing.RightWing2", 11, 14);
    setTextureOffset("RightWing.RightWing3", 4, 11);
    setTextureOffset("LeftWing.LeftWingStem", 82, 20);
    setTextureOffset("LeftWing.LeftWing1", 88, 17);
    setTextureOffset("LeftWing.LeftWing2", 95, 14);
    setTextureOffset("LeftWing.LeftWing3", 102, 11);
    
      LeftPauldron = new ModelRenderer(this, 82, 40);
      LeftPauldron.addBox(0F, -3F, -3F, 6, 4, 6);
      LeftPauldron.setRotationPoint(0F, 0F, 0F);
      LeftPauldron.setTextureSize(64, 32);
      LeftPauldron.mirror = true;
      setRotation(LeftPauldron, 0F, 0F, 0F);
      RightPauldron = new ModelRenderer(this, 26, 40);
      RightPauldron.addBox(-6F, -3F, -3F, 6, 4, 6);
      RightPauldron.setRotationPoint(0F, 0F, 0F);
      RightPauldron.setTextureSize(64, 32);
      RightPauldron.mirror = true;
      setRotation(RightPauldron, 0F, 0F, 0F);
      ChestPiece = new ModelRenderer(this, 50, 50);
      ChestPiece.addBox(-5F, -1F, -3F, 10, 13, 6);
      ChestPiece.setRotationPoint(0F, 0F, 0F);
      ChestPiece.setTextureSize(64, 32);
      ChestPiece.mirror = true;
      setRotation(ChestPiece, 0F, 0F, 0F);
      LeftElbow = new ModelRenderer(this, 84, 54);
      LeftElbow.addBox(-1F, 3F, -3F, 5, 5, 6);
      LeftElbow.setRotationPoint(0F, 0F, 0F);
      LeftElbow.setTextureSize(64, 32);
      LeftElbow.mirror = true;
      setRotation(LeftElbow, 0F, 0F, 0F);
      RightElbow = new ModelRenderer(this, 26, 54);
      RightElbow.addBox(-4F, 3F, -3F, 5, 5, 6);
      RightElbow.setRotationPoint(0F, 0F, 0F);
      RightElbow.setTextureSize(64, 32);
      RightElbow.mirror = true;
      setRotation(RightElbow, 0F, 0F, 0F);
      LeftPantLeg = new ModelRenderer(this, 66, 80);
      LeftPantLeg.addBox(-3F, 0F, -2.5F, 6, 8, 5);
      LeftPantLeg.setRotationPoint(0F, 0F, 0F);
      LeftPantLeg.setTextureSize(64, 32);
      LeftPantLeg.mirror = true;
      setRotation(LeftPantLeg, 0F, 0F, 0F);
      Helmet2 = new ModelRenderer(this, 52, 35);
      Helmet2.addBox(-4F, -5F, -5F, 1, 5, 1);
      Helmet2.setRotationPoint(0F, 0F, 0F);
      Helmet2.setTextureSize(64, 32);
      Helmet2.mirror = true;
      setRotation(Helmet2, 0F, 0F, 0F);
      Helmet3 = new ModelRenderer(this, 76, 35);
      Helmet3.addBox(3F, -5F, -5F, 1, 5, 1);
      Helmet3.setRotationPoint(0F, 0F, 0F);
      Helmet3.setTextureSize(64, 32);
      Helmet3.mirror = true;
      setRotation(Helmet3, 0F, 0F, 0F);
      Helmet4 = new ModelRenderer(this, 59, 36);
      Helmet4.addBox(-3F, -4F, -5F, 6, 4, 1);
      Helmet4.setRotationPoint(0F, 0F, 0F);
      Helmet4.setTextureSize(64, 32);
      Helmet4.mirror = true;
      setRotation(Helmet4, 0F, 0F, 0F);
      Helmet5 = new ModelRenderer(this, 28, 26);
      Helmet5.addBox(-5F, -5F, -5F, 1, 3, 10);
      Helmet5.setRotationPoint(0F, 0F, 0F);
      Helmet5.setTextureSize(64, 32);
      Helmet5.mirror = true;
      setRotation(Helmet5, 0F, 0F, 0F);
      Helmet6 = new ModelRenderer(this, 82, 26);
      Helmet6.addBox(4F, -5F, -5F, 1, 3, 10);
      Helmet6.setRotationPoint(0F, 0F, 0F);
      Helmet6.setTextureSize(64, 32);
      Helmet6.mirror = true;
      setRotation(Helmet6, 0F, 0F, 0F);
      Helmet7 = new ModelRenderer(this, 57, 28);
      Helmet7.addBox(-4F, -6F, 4F, 8, 5, 1);
      Helmet7.setRotationPoint(0F, 0F, 0F);
      Helmet7.setTextureSize(64, 32);
      Helmet7.mirror = true;
      setRotation(Helmet7, 0F, 0F, 0F);
      RightPantLeg = new ModelRenderer(this, 43, 80);
      RightPantLeg.addBox(-3F, 0F, -2.5F, 6, 8, 5);
      RightPantLeg.setRotationPoint(0F, 0F, 0F);
      RightPantLeg.setTextureSize(64, 32);
      RightPantLeg.mirror = true;
      setRotation(RightPantLeg, 0F, 0F, 0F);
      RightFoot = new ModelRenderer(this, 39, 94);
      RightFoot.addBox(-3F, 8F, -4.5F, 6, 5, 7);
      RightFoot.setRotationPoint(0F, 0F, 0F);
      RightFoot.setTextureSize(64, 32);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
      LeftFoot = new ModelRenderer(this, 66, 94);
      LeftFoot.addBox(-3F, 8F, -4.5F, 6, 5, 7);
      LeftFoot.setRotationPoint(0F, 0F, 0F);
      LeftFoot.setTextureSize(64, 32);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 0F, 0F);
      BackPlate = new ModelRenderer(this, 56, 42);
      BackPlate.addBox(-4F, 0F, 3F, 8, 5, 2);
      BackPlate.setRotationPoint(0F, 0F, 0F);
      BackPlate.setTextureSize(64, 32);
      BackPlate.mirror = true;
      setRotation(BackPlate, 0F, 0F, 0F);
    RightWing = new ModelRenderer(this, "RightWing");
    RightWing.setRotationPoint(-3F, 1F, 5F);
    setRotation(RightWing, 0F, 0F, 0F);
    RightWing.mirror = true;
      RightWing.addBox("RightWingStem", -10F, -1F, 0F, 10, 1, 1);
      RightWing.addBox("RightWing1", -12F, -2F, 0F, 10, 1, 1);
      RightWing.addBox("RightWing2", -14F, -3F, 0F, 10, 1, 1);
      RightWing.addBox("RightWing3", -16F, -4F, 0F, 10, 1, 1);
    LeftWing = new ModelRenderer(this, "LeftWing");
    LeftWing.setRotationPoint(3F, 1F, 5F);
    setRotation(LeftWing, 0F, 0F, 0F);
    LeftWing.mirror = true;
      LeftWing.addBox("LeftWingStem", 0F, -1F, 0F, 10, 1, 1);
      LeftWing.addBox("LeftWing1", 2F, -2F, 0F, 10, 1, 1);
      LeftWing.addBox("LeftWing2", 4F, -3F, 0F, 10, 1, 1);
      LeftWing.addBox("LeftWing3", 6F, -4F, 0F, 10, 1, 1);
      
      this.bipedBody.addChild(ChestPiece);
      this.bipedBody.addChild(BackPlate);
      this.bipedBody.addChild(LeftWing);
      this.bipedBody.addChild(RightWing);
      
      this.bipedHead.addChild(Helmet2);
      this.bipedHead.addChild(Helmet3);
      this.bipedHead.addChild(Helmet4);
      this.bipedHead.addChild(Helmet5);
      this.bipedHead.addChild(Helmet6);
      this.bipedHead.addChild(Helmet7);
      
      this.bipedLeftArm.addChild(LeftPauldron);
      this.bipedLeftArm.addChild(LeftElbow);
      
      this.bipedRightArm.addChild(RightPauldron);
      this.bipedRightArm.addChild(RightElbow);
      
      this.bipedRightLeg.addChild(RightPantLeg);
      this.bipedRightLeg.addChild(RightFoot);
      
      this.bipedLeftLeg.addChild(LeftPantLeg);
      this.bipedLeftLeg.addChild(LeftFoot);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    /*LeftPauldron.render(f5);
    RightPauldron.render(f5);
    ChestPiece.render(f5);
    LeftElbow.render(f5);
    RightElbow.render(f5);
    
    Helmet2.render(f5);
    Helmet3.render(f5);
    Helmet4.render(f5);
    Helmet5.render(f5);
    Helmet6.render(f5);
    Helmet7.render(f5);
    RightPantLeg.render(f5);
    LeftPantLeg.render(f5);
    RightFoot.render(f5);
    LeftFoot.render(f5);
    BackPlate.render(f5);
    RightWing.render(f5);
    LeftWing.render(f5);*/
    
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
