// Date: 6/6/2014 11:55:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLamp extends ModelBase
{
  //fields
    ModelRenderer LampBase1;
    ModelRenderer LampBase2;
    ModelRenderer LampShaft;
    ModelRenderer LampHood1;
    ModelRenderer LampHood2;
    ModelRenderer LampHood3;
    ModelRenderer LampHood4;
  
  public ModelLamp()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      LampBase1 = new ModelRenderer(this, 13, 52);
      LampBase1.addBox(0F, 0F, 0F, 10, 1, 10);
      LampBase1.setRotationPoint(-5F, 23F, -5F);
      LampBase1.setTextureSize(64, 64);
      LampBase1.mirror = true;
      setRotation(LampBase1, 0F, 0F, 0F);
      LampBase2 = new ModelRenderer(this, 17, 42);
      LampBase2.addBox(0F, 0F, 0F, 8, 1, 8);
      LampBase2.setRotationPoint(-4F, 22F, -4F);
      LampBase2.setTextureSize(64, 64);
      LampBase2.mirror = true;
      setRotation(LampBase2, 0F, 0F, 0F);
      LampShaft = new ModelRenderer(this, 54, 25);
      LampShaft.addBox(0F, 0F, 0F, 2, 22, 2);
      LampShaft.setRotationPoint(-1F, 0F, -1F);
      LampShaft.setTextureSize(64, 64);
      LampShaft.mirror = true;
      setRotation(LampShaft, 0F, 0F, 0F);
      LampHood1 = new ModelRenderer(this, 13, 25);
      LampHood1.addBox(0F, 0F, 0F, 10, 2, 10);
      LampHood1.setRotationPoint(-5F, -2F, -5F);
      LampHood1.setTextureSize(64, 64);
      LampHood1.mirror = true;
      setRotation(LampHood1, 0F, 0F, 0F);
      LampHood2 = new ModelRenderer(this, 17, 14);
      LampHood2.addBox(0F, 0F, 0F, 8, 2, 8);
      LampHood2.setRotationPoint(-4F, -4F, -4F);
      LampHood2.setTextureSize(64, 64);
      LampHood2.mirror = true;
      setRotation(LampHood2, 0F, 0F, 0F);
      LampHood3 = new ModelRenderer(this, 21, 6);
      LampHood3.addBox(0F, 0F, 0F, 6, 1, 6);
      LampHood3.setRotationPoint(-3F, -5F, -3F);
      LampHood3.setTextureSize(64, 64);
      LampHood3.mirror = true;
      setRotation(LampHood3, 0F, 0F, 0F);
      LampHood4 = new ModelRenderer(this, 24, 0);
      LampHood4.addBox(0F, 0F, 0F, 4, 1, 4);
      LampHood4.setRotationPoint(-2F, -6F, -2F);
      LampHood4.setTextureSize(64, 64);
      LampHood4.mirror = true;
      setRotation(LampHood4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    LampBase1.render(f5);
    LampBase2.render(f5);
    LampShaft.render(f5);
    LampHood1.render(f5);
    LampHood2.render(f5);
    LampHood3.render(f5);
    LampHood4.render(f5);
  }
  
  public void renderModel(float f)
  {
	LampBase1.render(f);
    LampBase2.render(f);
    LampShaft.render(f);
    LampHood1.render(f);
    LampHood2.render(f);
    LampHood3.render(f);
    LampHood4.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
