// Date: 7/27/2014 8:51:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelGentlemanCapybara extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer Head;
    ModelRenderer LegBackRight;
    ModelRenderer LegBackLeft;
    ModelRenderer LegFrontRight;
    ModelRenderer LegFrontLeft;
  
  public ModelGentlemanCapybara()
  {
    textureWidth = 64;
    textureHeight = 64;
    setTextureOffset("Body.MainBody", 13, 28);
    setTextureOffset("Head.HeadMain", 21, 51);
    setTextureOffset("Head.Neck", 27, 46);
    setTextureOffset("Head.EarLeft", 43, 50);
    setTextureOffset("Head.EarRight", 17, 50);
    setTextureOffset("Head.TopHat1", 20, 18);
    setTextureOffset("Head.TopHat2", 24, 8);
    setTextureOffset("LegBackRight.ThighBR", 7, 28);
    setTextureOffset("LegBackRight.AnkleBR", 7, 34);
    setTextureOffset("LegBackRight.FootBR", 5, 36);
    setTextureOffset("LegBackLeft.ThighBL", 51, 28);
    setTextureOffset("LegBackLeft.AnkleBL", 53, 34);
    setTextureOffset("LegBackLeft.FootBL", 51, 36);
    setTextureOffset("LegFrontRight.LegFR", 9, 42);
    setTextureOffset("LegFrontRight.FootFR", 5, 46);
    setTextureOffset("LegFrontLeft.LegFL", 51, 42);
    setTextureOffset("LegFrontLeft.FootFL", 51, 46);
    
    Body = new ModelRenderer(this, "Body");
    Body.setRotationPoint(0F, 16F, 1F);
    setRotation(Body, 0F, 0F, 0F);
    Body.mirror = true;
      Body.addBox("MainBody", -4F, -3F, -5F, 8, 7, 11);
    Head = new ModelRenderer(this, "Head");
    Head.setRotationPoint(0F, 16F, -4F);
    setRotation(Head, 0F, 0F, 0F);
    Head.mirror = true;
      Head.addBox("HeadMain", -2F, -3F, -8F, 4, 5, 7);
      Head.addBox("Neck", -2F, -2F, -1F, 4, 4, 1);
      Head.addBox("EarLeft", 2F, -3F, -2F, 1, 1, 1);
      Head.addBox("EarRight", -3F, -3F, -2F, 1, 1, 1);
      Head.addBox("TopHat1", -3F, -4F, -6F, 6, 1, 6);
      Head.addBox("TopHat2", -2F, -8F, -5F, 4, 4, 4);
    LegBackRight = new ModelRenderer(this, "LegBackRight");
    LegBackRight.setRotationPoint(-5F, 18F, 5F);
    setRotation(LegBackRight, 0F, 0F, 0F);
    LegBackRight.mirror = true;
      LegBackRight.addBox("ThighBR", 0F, 0F, -1F, 1, 4, 2);
      LegBackRight.addBox("AnkleBR", 0F, 4F, -1F, 1, 1, 1);
      LegBackRight.addBox("FootBR", -1F, 5F, -2F, 2, 1, 2);
    LegBackLeft = new ModelRenderer(this, "LegBackLeft");
    LegBackLeft.setRotationPoint(4F, 18F, 5F);
    setRotation(LegBackLeft, 0F, 0F, 0F);
    LegBackLeft.mirror = true;
      LegBackLeft.addBox("ThighBL", 0F, 0F, -1F, 1, 4, 2);
      LegBackLeft.addBox("AnkleBL", 0F, 4F, -1F, 1, 1, 1);
      LegBackLeft.addBox("FootBL", 0F, 5F, -2F, 2, 1, 2);
    LegFrontRight = new ModelRenderer(this, "LegFrontRight");
    LegFrontRight.setRotationPoint(-3F, 20F, -3F);
    setRotation(LegFrontRight, 0F, 0F, 0F);
    LegFrontRight.mirror = true;
      LegFrontRight.addBox("LegFR", 0F, 0F, 0F, 1, 3, 1);
      LegFrontRight.addBox("FootFR", -1F, 3F, -1F, 2, 1, 2);
    LegFrontLeft = new ModelRenderer(this, "LegFrontLeft");
    LegFrontLeft.setRotationPoint(2F, 20F, -3F);
    setRotation(LegFrontLeft, 0F, 0F, 0F);
    LegFrontLeft.mirror = true;
      LegFrontLeft.addBox("LegFL", 0F, 0F, 0F, 1, 3, 1);
      LegFrontLeft.addBox("FootFL", 0F, 3F, -1F, 2, 1, 2);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body.render(f5);
    Head.render(f5);
    LegBackRight.render(f5);
    LegBackLeft.render(f5);
    LegFrontRight.render(f5);
    LegFrontLeft.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.rotateAngleX = -(f4 / 57.29578F);   
    Head.rotateAngleY = f3 / 57.29578F;              
    Body.rotateAngleX = 0.0F; // we don't really want to rotate the body.        
    LegFrontRight.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;        
    LegFrontLeft.rotateAngleX = MathHelper.cos(f * 0.6662F + 3.141593F) * 1.4F * f1;       
    LegBackRight.rotateAngleX = MathHelper.cos(f * 0.6662F + 3.141593F) * 1.4F * f1;        
    LegBackLeft.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
  }

}
