// Date: 6/6/2014 10:10:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStatueSword extends ModelBase
{
  //fields
    ModelRenderer StatueBase1;
    ModelRenderer StatueBase2;
    ModelRenderer StatuePillar;
    ModelRenderer StatuePlatform;
    ModelRenderer StatueSwordBlade;
    ModelRenderer StatueSwordHilt;
    ModelRenderer StatueSwordHandle;
    ModelRenderer StatueBladeDet1;
    ModelRenderer StatueHiltDet1;
    ModelRenderer StatueHiltDet2;
    ModelRenderer StatueHandleDet1;
  
  public ModelStatueSword()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      StatueBase1 = new ModelRenderer(this, 34, 110);
      StatueBase1.addBox(0F, 0F, 0F, 16, 1, 16);
      StatueBase1.setRotationPoint(-8F, 23F, -8F);
      StatueBase1.setTextureSize(128, 128);
      StatueBase1.mirror = true;
      setRotation(StatueBase1, 0F, 0F, 0F);
      StatueBase2 = new ModelRenderer(this, 38, 94);
      StatueBase2.addBox(0F, 0F, 0F, 14, 1, 14);
      StatueBase2.setRotationPoint(-7F, 22F, -7F);
      StatueBase2.setTextureSize(128, 128);
      StatueBase2.mirror = true;
      setRotation(StatueBase2, 0F, 0F, 0F);
      StatuePillar = new ModelRenderer(this, 52, 74);
      StatuePillar.addBox(0F, 0F, 0F, 6, 12, 6);
      StatuePillar.setRotationPoint(-3F, 10F, -3F);
      StatuePillar.setTextureSize(128, 128);
      StatuePillar.mirror = true;
      setRotation(StatuePillar, 0F, 0F, 0F);
      StatuePlatform = new ModelRenderer(this, 39, 60);
      StatuePlatform.addBox(0F, 0F, 0F, 12, 1, 12);
      StatuePlatform.setRotationPoint(-6F, 9F, -6F);
      StatuePlatform.setTextureSize(128, 128);
      StatuePlatform.mirror = true;
      setRotation(StatuePlatform, 0F, 0F, 0F);
      StatueSwordBlade = new ModelRenderer(this, 65, 29);
      StatueSwordBlade.addBox(0F, 0F, 0F, 14, 1, 4);
      StatueSwordBlade.setRotationPoint(-3F, 8F, -2F);
      StatueSwordBlade.setTextureSize(128, 128);
      StatueSwordBlade.mirror = true;
      setRotation(StatueSwordBlade, 0F, 0F, 0F);
      StatueSwordHilt = new ModelRenderer(this, 46, 27);
      StatueSwordHilt.addBox(0F, 0F, 0F, 1, 1, 8);
      StatueSwordHilt.setRotationPoint(-4F, 8F, -4F);
      StatueSwordHilt.setTextureSize(128, 128);
      StatueSwordHilt.mirror = true;
      setRotation(StatueSwordHilt, 0F, 0F, 0F);
      StatueSwordHandle = new ModelRenderer(this, 30, 30);
      StatueSwordHandle.addBox(0F, 0F, 0F, 5, 1, 2);
      StatueSwordHandle.setRotationPoint(-9F, 8F, -1F);
      StatueSwordHandle.setTextureSize(128, 128);
      StatueSwordHandle.mirror = true;
      setRotation(StatueSwordHandle, 0F, 0F, 0F);
      StatueBladeDet1 = new ModelRenderer(this, 103, 30);
      StatueBladeDet1.addBox(0F, 0F, 0F, 1, 1, 2);
      StatueBladeDet1.setRotationPoint(11F, 8F, -1F);
      StatueBladeDet1.setTextureSize(128, 128);
      StatueBladeDet1.mirror = true;
      setRotation(StatueBladeDet1, 0F, 0F, 0F);
      StatueHiltDet1 = new ModelRenderer(this, 67, 24);
      StatueHiltDet1.addBox(0F, 0F, 0F, 2, 1, 1);
      StatueHiltDet1.setRotationPoint(-3F, 8F, 3F);
      StatueHiltDet1.setTextureSize(128, 128);
      StatueHiltDet1.mirror = true;
      setRotation(StatueHiltDet1, 0F, 0F, 0F);
      StatueHiltDet2 = new ModelRenderer(this, 67, 37);
      StatueHiltDet2.addBox(0F, 0F, 0F, 2, 1, 1);
      StatueHiltDet2.setRotationPoint(-3F, 8F, -4F);
      StatueHiltDet2.setTextureSize(128, 128);
      StatueHiltDet2.mirror = true;
      setRotation(StatueHiltDet2, 0F, 0F, 0F);
      StatueHandleDet1 = new ModelRenderer(this, 19, 28);
      StatueHandleDet1.addBox(0F, 0F, 0F, 1, 1, 4);
      StatueHandleDet1.setRotationPoint(-10F, 8F, -2F);
      StatueHandleDet1.setTextureSize(128, 128);
      StatueHandleDet1.mirror = true;
      setRotation(StatueHandleDet1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    StatueBase1.render(f5);
    StatueBase2.render(f5);
    StatuePillar.render(f5);
    StatuePlatform.render(f5);
    StatueSwordBlade.render(f5);
    StatueSwordHilt.render(f5);
    StatueSwordHandle.render(f5);
    StatueBladeDet1.render(f5);
    StatueHiltDet1.render(f5);
    StatueHiltDet2.render(f5);
    StatueHandleDet1.render(f5);
  }
  
  public void renderModel(float f)
  {
	StatueBase1.render(f);
    StatueBase2.render(f);
    StatuePillar.render(f);
    StatuePlatform.render(f);
    StatueSwordBlade.render(f);
    StatueSwordHilt.render(f);
    StatueSwordHandle.render(f);
    StatueBladeDet1.render(f);
    StatueHiltDet1.render(f);
    StatueHiltDet2.render(f);
    StatueHandleDet1.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
