// Date: 6/8/2014 11:27:38 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStool extends ModelBase
{
  //fields
    ModelRenderer FrontLeftLeg;
    ModelRenderer FrontRightLeg;
    ModelRenderer BackLeftLeg;
    ModelRenderer BackRightLeg;
    ModelRenderer Cushion;
  
  public ModelStool()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      FrontLeftLeg = new ModelRenderer(this, 1, 16);
      FrontLeftLeg.addBox(0F, -14F, 0F, 1, 14, 1);
      FrontLeftLeg.setRotationPoint(-4F, 24F, -4F);
      FrontLeftLeg.setTextureSize(32, 32);
      FrontLeftLeg.mirror = true;
      setRotation(FrontLeftLeg, -0.0523599F, 0F, 0.0523599F);
      FrontRightLeg = new ModelRenderer(this, 6, 16);
      FrontRightLeg.addBox(0F, -14F, 0F, 1, 14, 1);
      FrontRightLeg.setRotationPoint(3F, 24F, -4F);
      FrontRightLeg.setTextureSize(32, 32);
      FrontRightLeg.mirror = true;
      setRotation(FrontRightLeg, -0.0523599F, 0F, -0.0523599F);
      BackLeftLeg = new ModelRenderer(this, 22, 16);
      BackLeftLeg.addBox(0F, -14F, 0F, 1, 14, 1);
      BackLeftLeg.setRotationPoint(-4F, 24F, 3F);
      BackLeftLeg.setTextureSize(32, 32);
      BackLeftLeg.mirror = true;
      setRotation(BackLeftLeg, 0.0523599F, 0F, 0.0523599F);
      BackRightLeg = new ModelRenderer(this, 27, 16);
      BackRightLeg.addBox(0F, -14F, 0F, 1, 14, 1);
      BackRightLeg.setRotationPoint(3F, 24F, 3F);
      BackRightLeg.setTextureSize(32, 32);
      BackRightLeg.mirror = true;
      setRotation(BackRightLeg, 0.0523599F, 0F, -0.0523599F);
      Cushion = new ModelRenderer(this, 0, 2);
      Cushion.addBox(0F, 0F, 0F, 8, 3, 8);
      Cushion.setRotationPoint(-4F, 8F, -4F);
      Cushion.setTextureSize(32, 32);
      Cushion.mirror = true;
      setRotation(Cushion, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    FrontLeftLeg.render(f5);
    FrontRightLeg.render(f5);
    BackLeftLeg.render(f5);
    BackRightLeg.render(f5);
    Cushion.render(f5);
  }
  
  public void renderModel(float f)
  {
    FrontLeftLeg.render(f);
    FrontRightLeg.render(f);
    BackLeftLeg.render(f);
    BackRightLeg.render(f);
    Cushion.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
