// Date: 7/27/2014 12:40:15 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.DonLoughry.AllOfTheEverything.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWallpaper extends ModelBase
{
  //fields
    ModelRenderer LeftTile;
    ModelRenderer RightTile;
  
  public ModelWallpaper()
  {
    textureWidth = 36;
    textureHeight = 36;
    
      LeftTile = new ModelRenderer(this, 1, 1);
      LeftTile.addBox(0F, 0F, 0F, 16, 16, 1);
      LeftTile.setRotationPoint(-8F, 8F, 7F);
      LeftTile.setTextureSize(36, 36);
      LeftTile.mirror = true;
      setRotation(LeftTile, 0F, 0F, 0F);
      RightTile = new ModelRenderer(this, 1, 18);
      RightTile.addBox(0F, 0F, 0F, 16, 16, 1);
      RightTile.setRotationPoint(8F, 8F, 7F);
      RightTile.setTextureSize(36, 36);
      RightTile.mirror = true;
      setRotation(RightTile, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    LeftTile.render(f5);
    RightTile.render(f5);
  }
  
  public void renderModel(float f)
  {
	  LeftTile.render(f);
	  RightTile.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
